# Generic diffusion model configuration for EDM training
# Domain-agnostic configuration for unconditional diffusion training
# Can be used with any preprocessed .pt dataset

# Training hyperparameters
batch_size: 4
learning_rate: 0.0001
total_kimg: 200  # Training duration (adjust based on dataset size)

# EMA configuration
ema_halflife_kimg: 50

# Learning rate schedule
lr_rampup_kimg: 10

# Training progress
kimg_per_tick: 12
snapshot_ticks: 2

# Early stopping
early_stopping_patience: 5

# Model architecture
img_resolution: 256
channels: 3
model_channels: 192
channel_mult: [1, 2, 3, 4]

# Device and seed
device: cuda
seed: 42

# Dataset configuration
# Note: data_root and metadata_json are typically provided via command-line arguments
# The values below are defaults; override with --data_root and --metadata_json flags
data_root: dataset/processed
metadata_json: dataset/processed/metadata_photography_incremental.json
