# Fuji camera only configuration for EDM training
# This config trains exclusively on Fuji camera data from fuji/long train dataset

# Training hyperparameters
batch_size: 4
learning_rate: 0.0001
total_kimg: 200  # ~0.4 epochs over 51,840 training tiles (135 long images × 384 tiles)

# EMA configuration
ema_halflife_kimg: 50

# Learning rate schedule
lr_rampup_kimg: 10

# Training progress
kimg_per_tick: 12
snapshot_ticks: 2

# Early stopping
early_stopping_patience: 5

# Model architecture
img_resolution: 256
channels: 3
model_channels: 192
channel_mult: [1, 2, 3, 4]

# Device and seed
device: cuda
seed: 42

# Dataset configuration
data_root: dataset/processed/pt_tiles/fuji
metadata_json: dataset/processed/metadata_fuji_incremental.json
# Note: Training code automatically filters for long exposure data only
# The SimplePTDataset class handles filtering out short exposure tiles
