# Microscopy domain configuration
# Overrides for default.yaml
# Based on actual data from metadata_microscopy_incremental.json
# Electron range: ~1158 - 65534 electrons (95th percentile: ~65534)

# Physical parameters (from actual dataset statistics)
physics:
  s: 65534.0  # Scale factor (95th percentile electron_max from data)
  sigma_r: 1.5  # Read noise (all tiles have 1.5 electrons)
  background: 0.0  # Background level (mean is low)

# Domain configuration
domain:
  type: "micro"

# Data configuration
data:
  image_size: 512  # Microscopy images often larger
  target_size: 128
  channels: 1  # Often single-channel fluorescence

# Guidance configuration
guidance:
  enabled: true
  mode: "wls"
  kappa: 0.7  # Stronger guidance for low photon counts
  tau: 0.01

# Sampling configuration
sampling:
  num_steps: 50
  sigma_min: 0.002
  sigma_max: 80.0
  rho: 7.0

# Training specific
training:
  data_root: "/home/jilab/Jae/dataset/processed/png_tiles/microscopy"
  max_steps: 200000
  batch_size: 1
  gradient_accumulation_steps: 4
  learning_rate: 5.0e-6
  target_size: 128
