# Photography domain configuration for EDM training
# This config is used by run_edm_pt_photography_train.sh and train_pt_edm_native_photography.py

# Training hyperparameters
batch_size: 4
learning_rate: 0.0001
total_kimg: 300

# EMA configuration
ema_halflife_kimg: 50

# Learning rate schedule
lr_rampup_kimg: 10

# Training progress
kimg_per_tick: 12
snapshot_ticks: 2

# Early stopping
early_stopping_patience: 5

# Model architecture
img_resolution: 256
channels: 3
model_channels: 192
channel_mult: [1, 2, 3, 4]

# Device and seed
device: cuda
seed: 42
