# Sony + Fuji cameras combined configuration for EDM training
# This config trains on both Sony and Fuji camera data from sony/long and fuji/long train datasets

# Training hyperparameters
batch_size: 4
learning_rate: 0.0001
total_kimg: 40  # ~0.5 epochs over 86,616 training tiles (296 long images × 216/384 tiles)

# EMA configuration
ema_halflife_kimg: 50

# Learning rate schedule
lr_rampup_kimg: 10

# Training progress
kimg_per_tick: 12
snapshot_ticks: 2

# Early stopping
early_stopping_patience: 5

# Model architecture
img_resolution: 256
channels: 3
model_channels: 192
channel_mult: [1, 2, 3, 4]

# Device and seed
device: cuda
seed: 42

# Dataset configuration
data_root: dataset/processed
metadata_json: dataset/processed/metadata_photography_incremental.json
# Note: Currently trains on all sensors. To filter by sensor type, create separate metadata files
# sensor_types: [sony, fuji]  # NOT CURRENTLY SUPPORTED - requires metadata filtering or dataset modifications
