# Sony camera only configuration for EDM training
# This config trains exclusively on Sony camera data from sony/long train dataset

# Training hyperparameters
batch_size: 4
learning_rate: 0.0001
total_kimg: 300

# EMA configuration
ema_halflife_kimg: 50

# Learning rate schedule
lr_rampup_kimg: 10

# Training progress
kimg_per_tick: 12
snapshot_ticks: 2

# Early stopping
early_stopping_patience: 5

# Model architecture
img_resolution: 256
channels: 3
model_channels: 192
channel_mult: [1, 2, 3, 4]

# Device and seed
device: cuda
seed: 42

# Dataset configuration (Sony specific)
data_root: dataset/processed  # Dataset loader will find sony/long subdirectory automatically
metadata_json: dataset/processed/metadata_photography_incremental.json
sensor_types: [sony]  # Only train on Sony camera tiles
# Note: Metadata JSON contains all tiles, but training will only use 'long' exposure tiles
