# Baseline Evaluation Configuration
# Configuration for comprehensive baseline method comparison

# General settings
device: 'auto'  # 'cuda', 'cpu', or 'auto'
seed: 42
output_dir: 'baseline_evaluation_results'

# Evaluation settings
evaluation:
  # Domains to evaluate
  domains:
    - 'photography'
    - 'microscopy'
    - 'astronomy'

  # Metrics to compute
  metrics:
    - 'psnr'
    - 'ssim'
    - 'lpips'
    - 'ms_ssim'
    - 'chi2_consistency'
    - 'residual_whiteness'
    - 'bias_analysis'

  # Output settings
  save_individual_results: true
  save_visualizations: true
  save_sample_images: true

  # Statistical analysis
  confidence_intervals: true
  significance_testing: true
  multiple_comparisons_correction: 'bonferroni'

# Baseline method configuration
baselines:
  # Classical methods
  classical:
    bm3d:
      enabled: true
      # BM3D will be used if available, otherwise skipped

    anscombe_bm3d:
      enabled: true
      # Anscombe + BM3D for Poisson noise

    richardson_lucy:
      enabled: true
      num_iterations: 10

    gaussian:
      enabled: true
      sigma: 1.0

    wiener:
      enabled: true
      noise_variance: 0.01

  # Deep learning methods
  deep_learning:
    dncnn:
      enabled: true
      num_layers: 17
      model_path: null  # Use built-in implementation

    nafnet:
      enabled: true
      model_path: null  # Use built-in implementation

  # Self-supervised methods
  self_supervised:
    noise2void:
      enabled: true
      mask_ratio: 0.1

  # Diffusion baselines (requires external model)
  diffusion:
    l2_guided:
      enabled: false  # Set to true if diffusion model available
      steps: 18
      guidance_weight: 1.0

# Synthetic data generation settings
synthetic_data:
  # Number of samples per domain
  num_samples: 100

  # Image sizes to test
  image_sizes:
    - [128, 128]
    - [256, 256]
    - [512, 512]

  # Noise levels (read noise in electrons)
  noise_levels:
    photography: [3, 5, 10, 15]
    microscopy: [1, 2, 3, 5]
    astronomy: [1, 2, 3]

  # Signal levels (scale in electrons)
  signal_levels:
    photography: [1000, 5000, 10000]
    microscopy: [500, 2000, 5000]
    astronomy: [10000, 25000, 50000]

  # Background levels (electrons)
  background_levels:
    photography: [100, 300, 500]
    microscopy: [50, 100, 200]
    astronomy: [0, 50, 100]

# Real data loading settings
real_data:
  # Expected directory structure:
  # data_root/
  #   photography/
  #     noisy/
  #     clean/
  #   microscopy/
  #     noisy/
  #     clean/
  #   astronomy/
  #     noisy/
  #     clean/

  # File matching
  match_by_name: true  # Match noisy/clean by filename
  supported_formats:
    photography: ['.arw', '.dng', '.nef', '.cr2']
    microscopy: ['.tif', '.tiff']
    astronomy: ['.fits', '.fit']

  # Preprocessing
  normalize_input: true
  crop_to_multiple: 8  # Crop to multiple of 8 for network compatibility

# Visualization settings
visualization:
  # Plot settings
  figure_size: [12, 8]
  dpi: 300
  style: 'seaborn-v0_8'

  # Metrics to plot
  plot_metrics:
    - 'psnr'
    - 'ssim'
    - 'chi2_consistency'
    - 'processing_times'

  # Comparison plots
  create_cross_domain_plots: true
  create_method_ranking_plots: true
  create_statistical_plots: true

  # Sample visualization
  save_sample_comparisons: true
  num_sample_comparisons: 5

# Reporting settings
reporting:
  # Report format
  format: 'markdown'  # 'markdown', 'html', 'pdf'

  # Content sections
  include_executive_summary: true
  include_method_descriptions: true
  include_statistical_analysis: true
  include_recommendations: true

  # Tables and figures
  include_summary_tables: true
  include_detailed_tables: true
  include_plots: true

  # Statistical reporting
  report_confidence_intervals: true
  report_effect_sizes: true
  report_significance_tests: true

# Performance settings
performance:
  # Parallel processing
  num_workers: 4
  batch_size: 8

  # Memory management
  clear_cache_between_methods: true
  use_mixed_precision: false  # Set to true for faster evaluation

  # Checkpointing
  save_intermediate_results: true
  checkpoint_frequency: 10  # Save every N samples

# Logging settings
logging:
  level: 'INFO'
  log_to_file: true
  log_file: 'baseline_evaluation.log'

  # Progress reporting
  show_progress_bars: true
  report_timing: true

  # Debug settings
  debug_mode: false
  save_debug_info: false

# Quality assurance
quality_assurance:
  # Validation checks
  validate_inputs: true
  check_output_ranges: true
  verify_metric_consistency: true

  # Error handling
  continue_on_error: true
  max_errors_per_method: 5

  # Reproducibility
  set_random_seeds: true
  save_environment_info: true
