# Domain-specific guidance configurations optimized for each imaging modality

# Photography domain - moderate noise, good SNR
photography:
  mode: "wls"  # WLS is sufficient for photography
  gamma_schedule: "sigma2"
  kappa: 0.5  # Standard strength
  gradient_clip: 10.0
  variance_eps: 0.1
  adaptive_kappa: false
  normalize_gradients: false
  collect_diagnostics: true

  # Photography-specific optimizations
  enable_masking: true
  max_diagnostics: 1000

# Microscopy domain - low photon counts, need careful guidance
microscopy:
  mode: "wls"  # WLS with higher strength
  gamma_schedule: "sigma2"
  kappa: 0.8  # Higher for low photon counts
  gradient_clip: 5.0  # More conservative clipping
  variance_eps: 0.05  # Smaller epsilon for precision
  adaptive_kappa: true  # Adapt to very low signals
  normalize_gradients: false
  collect_diagnostics: true

  # Microscopy-specific optimizations
  enable_masking: true
  max_diagnostics: 1000

# Astronomy domain - extreme low-light, highest guidance needed
astronomy:
  mode: "exact"  # Use exact likelihood for maximum accuracy
  gamma_schedule: "linear"  # Better for very low SNR
  kappa: 1.0  # Highest guidance strength
  gradient_clip: 20.0  # Allow larger corrections for faint sources
  variance_eps: 0.01  # Very small epsilon for precision
  adaptive_kappa: true  # Essential for varying signal levels
  normalize_gradients: true  # Help with extreme gradients
  collect_diagnostics: true

  # Astronomy-specific optimizations
  enable_masking: true  # Critical for cosmic ray rejection
  max_diagnostics: 1000

# Conservative preset for unknown domains
conservative:
  mode: "wls"
  gamma_schedule: "const"
  kappa: 0.3  # Lower strength for safety
  gradient_clip: 5.0
  variance_eps: 0.1
  adaptive_kappa: false
  normalize_gradients: false
  collect_diagnostics: true
  enable_masking: true
  max_diagnostics: 500

# High-performance preset for fast inference
fast:
  mode: "wls"
  gamma_schedule: "const"
  kappa: 0.5
  gradient_clip: 10.0
  variance_eps: 0.1
  adaptive_kappa: false
  normalize_gradients: false
  collect_diagnostics: false  # Disable for speed
  enable_masking: false  # Disable for speed
  max_diagnostics: 0
