# L2 Baseline Training Configuration - Astronomy Domain
# Identical to main config except guidance type

# Model configuration - Identical to Poisson-Gaussian
model:
  architecture: "EDM"
  img_channels: 1
  img_resolution: 128
  model_channels: 256
  channel_mult: [1, 2, 3, 4]
  channel_mult_emb: 6
  num_blocks: 6
  attn_resolutions: [16, 32, 64]
  condition_dim: 6
  dropout: 0.1

# Training configuration - Identical
training:
  batch_size: 16
  learning_rate: 2e-4
  num_epochs: 100
  gradient_clip: 1.0
  mixed_precision: true
  scheduler: "cosine"
  warmup_epochs: 5
  min_lr: 1e-6
  accumulate_grad_batches: 2
  optimizer: "adamw"
  weight_decay: 1e-2
  beta1: 0.9
  beta2: 0.999
  experiment_name: "l2_baseline_astronomy"
  deterministic: true
  seed: 42  # Same seed for fair comparison

# Sampling configuration - Identical
sampling:
  steps: 18
  sigma_min: 0.002
  sigma_max: 80.0
  rho: 7.0
  guidance_weight: 1.0

# Data configuration - Identical
data:
  domains: ["astronomy"]
  target_size: 128
  patch_size: null
  augment: true
  num_workers: 8
  pin_memory: true
  persistent_workers: true
  prefetch_factor: 2
  scale: 200.0
  background: 20.0
  read_noise: 2.0

# Domain configurations - Identical
domains:
  astronomy:
    pixel_size: 0.04
    pixel_unit: "arcsec"
    extensions: [".fits", ".fit"]
    black_level: 0
    white_level: 65535

# Guidance configuration - ONLY DIFFERENCE FROM MAIN CONFIG
guidance:
  type: "l2"  # Only difference from main config
  mode: "wls"  # Keep same for consistency
  gamma_schedule: "sigma2"  # Identical scheduling
  kappa: 0.5  # Identical strength
  gradient_clip: 100.0  # Identical stability

# Evaluation configuration - Identical
evaluation:
  metrics: ["psnr", "ssim", "lpips", "chi2_consistency"]
  save_images: true
  compute_physics_metrics: true

# Logging and output - Identical
logging:
  level: "INFO"
  log_file: "logs/l2_baseline_astronomy.log"

output:
  checkpoint_dir: "checkpoints/l2_baseline_astronomy"
  results_dir: "results/l2_baseline_astronomy"
  save_frequency: 10
